### ISSUE TITLE
Feature request: hotkey/command to quickly disable/enable

### ISSUE THREAD

**Issue by Mathsterk** [jfcherng-sublime/ST-RainbowIndent#1]
It would be nice if you could bind a hotkey and/or use a command to quickly disable or enable the coloring of the indents.

**Comment by jfcherng** [comment]
Added in https://github.com/jfcherng-sublime/ST-RainbowIndent/commit/dc77bfc25f4eb56a9a89b8f9aad649876eed3add. Released as `v0.1.0`.

**Comment by jfcherng** [comment]
3 new commands without default keybindings.

- rainbow_indent_view_disable
- rainbow_indent_view_enable
- rainbow_indent_view_toggle

I would expect users only use `rainbow_indent_view_toggle` though.
