### ISSUE TITLE
[Feature] Being able to exclude file types

### ISSUE THREAD

**Issue by Draghmar** [jfcherng-sublime/ST-RainbowIndent#2]
Hi.
Nice addition to the ST plugins repo!
It would be great to have a way to exclude some file types from being parsed. For example I really don't need CSS files to have indentation emphasized this way. ;)

**Comment by jfcherng** [comment]
You can use the following plugin settings in the next release v0.1.4 to exclude CSS files. 

```js
    // Enable this plugin in these base scopes.
    // For the expression of a scope selector, see https://www.sublimetext.com/docs/selectors.html
    "enabled_selector": "source - source.css | text | embedding",
```

The new release will be available within 3 hours.
