### ISSUE TITLE
[Feature] Automatically config scope in settings

### ISSUE THREAD

**Issue by I-AM-A-NOOB** [jfcherng-sublime/ST-RainbowIndent#4]
[RainbowBrackets](https://github.com/absop/RainbowBrackets) creates its standalone colour schemes only containing the scope of the rainbow brackets at `~\AppData\Roaming\Sublime Text\Packages\User\Color Schemes\RainbowBrackets` which contains scopes referring to it's settings. I think there might be a possible way to manage scope in the `.sublime-settings` file then automatically apply it to a standalone `.sublime-color-scheme` in the user profile like the behaviour of RainbowBrackets instead of modifying the default colour scheme which might lead to **confusion and unstability**. what confused me is that I can't find the original `breakers.sublime-color-scheme` file. By the way, if this is taken into consideration, please be compatible with RainbowBrackets.

**Comment by jfcherng** [comment]
I won't do any auto modification to user's color scheme, nor user settings. I hate that EXTREMELY.

**Comment by jfcherng** [comment]
The sane way imho is https://github.com/sublimehq/sublime_text/issues/6381
