### ISSUE TITLE
[Feature] Ability to set how many newlines is required for a break in the coloring

### ISSUE THREAD

**Issue by Mathsterk** [jfcherng-sublime/ST-RainbowIndent#5]
It would be nice to be able to change how many newlines is required for the colored line/bar to break, it would make it look a bit neater. I like using newlines to break code up into smaller blocks, but it makes the indents look a bit wonky, so having a continuous line would look better, but i also want them to break when i use multiple newlines between functions etc.
![image](https://github.com/user-attachments/assets/90bdd36b-7eed-4cf9-9fa8-fe692a4d671e)

**Comment by jfcherng** [comment]
https://github.com/jfcherng-sublime/ST-RainbowIndent#known-issues

> Known Issues
> There is no way to draw a region, where is no character, via ST's plugin APIs.

**Comment by Mathsterk** [comment]
Ah, i see. I will have to find some other solution then, thanks for the answer and the plugin :)

**Comment by jfcherng** [comment]
> Ah, i see. I will have to find some other solution then, thanks for the answer and the plugin :)

It looks better with transparent background imho.

![image](https://github.com/user-attachments/assets/63e23f6f-de2f-4ce4-a8a4-942006d16389)
